"""Apollo.io API Client.

Async Python client for Apollo.io CRM API with full type safety.
"""

from .client import ApolloClient
from .exceptions import APIError, ApolloError, AuthenticationError, RateLimitError
from .models import (
    Account,
    AccountDetail,
    AccountPlaybookStatus,
    AccountQueue,
    ApolloModel,
    CalendarEvent,
    CalendarEventParticipant,
    Call,
    Contact,
    ContactCampaignStatus,
    ContactDetail,
    ContactEmailEntry,
    ContactJobChangeEvent,
    ContactRole,
    ContactRuleConfigStatus,
    CrmJob,
    CrmNote,
    Currency,
    Deal,
    Email,
    EmailerMessage,
    EmailParticipant,
    EmploymentHistory,
    EngagementData,
    EngagementGraphEntry,
    EngagementTypeCount,
    JobPosting,
    NewsArticle,
    Note,
    OpportunityContactRole,
    OpportunityRoleEntry,
    OrganizationRef,
    PaginatedResponse,
    PhoneEntry,
    Pipeline,
    Stage,
    Task,
    TaskType,
    Technology,
)

__all__ = [
    "APIError",
    "Account",
    "AccountDetail",
    "AccountPlaybookStatus",
    "AccountQueue",
    "ApolloClient",
    "ApolloError",
    "ApolloModel",
    "AuthenticationError",
    "CalendarEvent",
    "CalendarEventParticipant",
    "Call",
    "Contact",
    "ContactCampaignStatus",
    "ContactDetail",
    "ContactEmailEntry",
    "ContactJobChangeEvent",
    "ContactRole",
    "ContactRuleConfigStatus",
    "CrmJob",
    "CrmNote",
    "Currency",
    "Deal",
    "Email",
    "EmailParticipant",
    "EmailerMessage",
    "EmploymentHistory",
    "EngagementData",
    "EngagementGraphEntry",
    "EngagementTypeCount",
    "JobPosting",
    "NewsArticle",
    "Note",
    "OpportunityContactRole",
    "OpportunityRoleEntry",
    "OrganizationRef",
    "PaginatedResponse",
    "PhoneEntry",
    "Pipeline",
    "RateLimitError",
    "Stage",
    "Task",
    "TaskType",
    "Technology",
]

__version__ = "0.1.0"
